name: Update Version


on:
  pull_request:
    types: [closed]
    branches:
      - staging
    

jobs:
  create-version:
    name: Update version
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get current bundle version
        id: package_version
        uses: KageKirin/get-unity-bundle-version@v0
        
      - name: Bump version
        id: bump_version_minor
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ steps.package_version.outputs.version }}
          increment-version-fragment: 'MINOR'

      - name: Set version minor
        id: package_version_set_major
        uses: KageKirin/set-unity-bundle-version@v0
        with:
          version: ${{ steps.bump_version_minor.outputs.updated-version }}
          
          
      - name: Push changed files back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: staging
          commit_message: "Updated semver via automated action."
          commit_options: '--no-verify --signoff'
          
